### ISSUE TITLE
registered_courses initialized to None while creating gcal events

### ISSUE THREAD

**Issue by plaidbait91** [pnicto/erp2gcal#7]
### Machine and browser details

- Ubuntu 20.04.5 LTS
- Mozilla Firefox 107.0
- Python version: 3.10

### To reproduce issue

`python3.10 main.py c firefox`

### Logs
```

invalid literal for int() with base 10: 'TBA'
Till when the events should be created?
Enter date in YYYY/MM/DD format [date excluded] eg:2023/01/05
2023/05/07

Creating events
Traceback (most recent call last):
  File "/home/srikant/erp2gcal/main.py", line 68, in <module>
    run(main)
  File "/home/srikant/erp2gcal/env/lib/python3.10/site-packages/sigtools/modifiers.py", line 161, in __call__
    return self.func(*args, **kwargs)
  File "/home/srikant/erp2gcal/env/lib/python3.10/site-packages/clize/runner.py", line 395, in run
    ret = cli(*args)
  File "/home/srikant/erp2gcal/env/lib/python3.10/site-packages/clize/runner.py", line 262, in __call__
    return func(*posargs, **kwargs)
  File "/home/srikant/erp2gcal/main.py", line 54, in main
    gcal_actions.create_calendar_events(registered_courses)
  File "/home/srikant/erp2gcal/src/gcal_actions.py", line 51, in create_calendar_events
    for course in registered_courses:
TypeError: 'NoneType' object is not iterable

```
Should be a simple fix to handle how "TBA" values are treated while scraping ERP timetable, I'll try fixing this and putting a PR

**Comment by pnicto** [comment]
Can you send your student center timetable? (not the weekly schedule).

**Comment by plaidbait91** [comment]
![image](https://user-images.githubusercontent.com/75108809/215147573-c60d3a39-4ba8-4e92-925d-c693ffa50a2b.png)
This is the registered_course_str_list array

**Comment by pnicto** [comment]
The project course (CS F367) is the edge case. The current parser expects timings which projects do not have and also is something I overlooked.


I will update the parser soon™. Hopefully by Sunday.
